/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Reminder {
    clientName: string;
    appointmentTime: bigint;
    reminderType: string;
    message: string;
}
export type Time = bigint;
export interface FinancialRecord {
    id: bigint;
    linkedAppointmentId?: bigint;
    date: Time;
    description: string;
    category: string;
    amount: number;
    financialType: FinancialType;
}
export interface Client {
    id: bigint;
    name: string;
    businessType: BusinessType;
    email: string;
    lastVisit: Time;
    notes: string;
    totalVisits: bigint;
    phone: string;
}
export interface Appointment {
    id: bigint;
    service: string;
    status: AppointmentStatus;
    duration: bigint;
    clientId: bigint;
    notes: string;
    dateTime: Time;
}
export enum AppointmentStatus {
    scheduled = "scheduled",
    cancelled = "cancelled",
    completed = "completed"
}
export enum BusinessType {
    clinic = "clinic",
    barber = "barber",
    salon = "salon",
    petshop = "petshop"
}
export enum FinancialType {
    expense = "expense",
    income = "income"
}
export interface backendInterface {
    createAppointment(clientId: bigint, service: string, dateTime: Time, duration: bigint, notes: string): Promise<Appointment>;
    createClient(name: string, phone: string, email: string, businessType: BusinessType): Promise<Client>;
    createFinancialRecord(financialType: FinancialType, amount: number, category: string, date: Time, description: string, linkedAppointmentId: bigint | null): Promise<FinancialRecord>;
    deleteAppointment(id: bigint): Promise<void>;
    deleteClient(id: bigint): Promise<void>;
    deleteFinancialRecord(id: bigint): Promise<void>;
    generateMessageTemplates(clientId: bigint, daysSinceLastVisit: bigint): Promise<Array<string>>;
    generateReminders(): Promise<Array<Reminder>>;
    getAppointment(id: bigint): Promise<Appointment>;
    getClient(id: bigint): Promise<Client>;
    getClientsNotVisitedSince(days: bigint): Promise<Array<Client>>;
    getFinancialRecord(id: bigint): Promise<FinancialRecord>;
    getTopClientsByVisits(limit: bigint): Promise<Array<Client>>;
    getTotalAppointments(): Promise<bigint>;
    getTotalClients(): Promise<bigint>;
    getTotalFinancialRecords(): Promise<bigint>;
    updateAppointmentStatus(id: bigint, status: AppointmentStatus): Promise<Appointment>;
    updateClient(id: bigint, name: string, phone: string, email: string, businessType: BusinessType, notes: string): Promise<Client>;
}
import type { Appointment as _Appointment, AppointmentStatus as _AppointmentStatus, BusinessType as _BusinessType, Client as _Client, FinancialRecord as _FinancialRecord, FinancialType as _FinancialType, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createAppointment(arg0: bigint, arg1: string, arg2: Time, arg3: bigint, arg4: string): Promise<Appointment> {
        if (this.processError) {
            try {
                const result = await this.actor.createAppointment(arg0, arg1, arg2, arg3, arg4);
                return from_candid_Appointment_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAppointment(arg0, arg1, arg2, arg3, arg4);
            return from_candid_Appointment_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createClient(arg0: string, arg1: string, arg2: string, arg3: BusinessType): Promise<Client> {
        if (this.processError) {
            try {
                const result = await this.actor.createClient(arg0, arg1, arg2, to_candid_BusinessType_n5(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Client_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClient(arg0, arg1, arg2, to_candid_BusinessType_n5(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Client_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async createFinancialRecord(arg0: FinancialType, arg1: number, arg2: string, arg3: Time, arg4: string, arg5: bigint | null): Promise<FinancialRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.createFinancialRecord(to_candid_FinancialType_n11(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg5));
                return from_candid_FinancialRecord_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFinancialRecord(to_candid_FinancialType_n11(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg5));
            return from_candid_FinancialRecord_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteAppointment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAppointment(arg0);
            return result;
        }
    }
    async deleteClient(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClient(arg0);
            return result;
        }
    }
    async deleteFinancialRecord(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFinancialRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFinancialRecord(arg0);
            return result;
        }
    }
    async generateMessageTemplates(arg0: bigint, arg1: bigint): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.generateMessageTemplates(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateMessageTemplates(arg0, arg1);
            return result;
        }
    }
    async generateReminders(): Promise<Array<Reminder>> {
        if (this.processError) {
            try {
                const result = await this.actor.generateReminders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateReminders();
            return result;
        }
    }
    async getAppointment(arg0: bigint): Promise<Appointment> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointment(arg0);
                return from_candid_Appointment_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointment(arg0);
            return from_candid_Appointment_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClient(arg0: bigint): Promise<Client> {
        if (this.processError) {
            try {
                const result = await this.actor.getClient(arg0);
                return from_candid_Client_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClient(arg0);
            return from_candid_Client_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClientsNotVisitedSince(arg0: bigint): Promise<Array<Client>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClientsNotVisitedSince(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClientsNotVisitedSince(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFinancialRecord(arg0: bigint): Promise<FinancialRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getFinancialRecord(arg0);
                return from_candid_FinancialRecord_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFinancialRecord(arg0);
            return from_candid_FinancialRecord_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopClientsByVisits(arg0: bigint): Promise<Array<Client>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopClientsByVisits(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopClientsByVisits(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalAppointments(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalAppointments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalAppointments();
            return result;
        }
    }
    async getTotalClients(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalClients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalClients();
            return result;
        }
    }
    async getTotalFinancialRecords(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalFinancialRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalFinancialRecords();
            return result;
        }
    }
    async updateAppointmentStatus(arg0: bigint, arg1: AppointmentStatus): Promise<Appointment> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAppointmentStatus(arg0, to_candid_AppointmentStatus_n20(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Appointment_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAppointmentStatus(arg0, to_candid_AppointmentStatus_n20(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Appointment_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateClient(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: BusinessType, arg5: string): Promise<Client> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClient(arg0, arg1, arg2, arg3, to_candid_BusinessType_n5(this._uploadFile, this._downloadFile, arg4), arg5);
                return from_candid_Client_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClient(arg0, arg1, arg2, arg3, to_candid_BusinessType_n5(this._uploadFile, this._downloadFile, arg4), arg5);
            return from_candid_Client_n7(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AppointmentStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppointmentStatus): AppointmentStatus {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Appointment_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Appointment): Appointment {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_BusinessType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BusinessType): BusinessType {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Client_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Client): Client {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_FinancialRecord_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FinancialRecord): FinancialRecord {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_FinancialType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FinancialType): FinancialType {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    linkedAppointmentId: [] | [bigint];
    date: _Time;
    description: string;
    category: string;
    amount: number;
    financialType: _FinancialType;
}): {
    id: bigint;
    linkedAppointmentId?: bigint;
    date: Time;
    description: string;
    category: string;
    amount: number;
    financialType: FinancialType;
} {
    return {
        id: value.id,
        linkedAppointmentId: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.linkedAppointmentId)),
        date: value.date,
        description: value.description,
        category: value.category,
        amount: value.amount,
        financialType: from_candid_FinancialType_n17(_uploadFile, _downloadFile, value.financialType)
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    service: string;
    status: _AppointmentStatus;
    duration: bigint;
    clientId: bigint;
    notes: string;
    dateTime: _Time;
}): {
    id: bigint;
    service: string;
    status: AppointmentStatus;
    duration: bigint;
    clientId: bigint;
    notes: string;
    dateTime: Time;
} {
    return {
        id: value.id,
        service: value.service,
        status: from_candid_AppointmentStatus_n3(_uploadFile, _downloadFile, value.status),
        duration: value.duration,
        clientId: value.clientId,
        notes: value.notes,
        dateTime: value.dateTime
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    businessType: _BusinessType;
    email: string;
    lastVisit: _Time;
    notes: string;
    totalVisits: bigint;
    phone: string;
}): {
    id: bigint;
    name: string;
    businessType: BusinessType;
    email: string;
    lastVisit: Time;
    notes: string;
    totalVisits: bigint;
    phone: string;
} {
    return {
        id: value.id,
        name: value.name,
        businessType: from_candid_BusinessType_n9(_uploadFile, _downloadFile, value.businessType),
        email: value.email,
        lastVisit: value.lastVisit,
        notes: value.notes,
        totalVisits: value.totalVisits,
        phone: value.phone
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    clinic: null;
} | {
    barber: null;
} | {
    salon: null;
} | {
    petshop: null;
}): BusinessType {
    return "clinic" in value ? BusinessType.clinic : "barber" in value ? BusinessType.barber : "salon" in value ? BusinessType.salon : "petshop" in value ? BusinessType.petshop : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expense: null;
} | {
    income: null;
}): FinancialType {
    return "expense" in value ? FinancialType.expense : "income" in value ? FinancialType.income : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: null;
} | {
    cancelled: null;
} | {
    completed: null;
}): AppointmentStatus {
    return "scheduled" in value ? AppointmentStatus.scheduled : "cancelled" in value ? AppointmentStatus.cancelled : "completed" in value ? AppointmentStatus.completed : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Client>): Array<Client> {
    return value.map((x)=>from_candid_Client_n7(_uploadFile, _downloadFile, x));
}
function to_candid_AppointmentStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentStatus): _AppointmentStatus {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_BusinessType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BusinessType): _BusinessType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_FinancialType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FinancialType): _FinancialType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FinancialType): {
    expense: null;
} | {
    income: null;
} {
    return value == FinancialType.expense ? {
        expense: null
    } : value == FinancialType.income ? {
        income: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentStatus): {
    scheduled: null;
} | {
    cancelled: null;
} | {
    completed: null;
} {
    return value == AppointmentStatus.scheduled ? {
        scheduled: null
    } : value == AppointmentStatus.cancelled ? {
        cancelled: null
    } : value == AppointmentStatus.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BusinessType): {
    clinic: null;
} | {
    barber: null;
} | {
    salon: null;
} | {
    petshop: null;
} {
    return value == BusinessType.clinic ? {
        clinic: null
    } : value == BusinessType.barber ? {
        barber: null
    } : value == BusinessType.salon ? {
        salon: null
    } : value == BusinessType.petshop ? {
        petshop: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
