/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const AppointmentStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
});
export const Appointment = IDL.Record({
  'id' : IDL.Nat,
  'service' : IDL.Text,
  'status' : AppointmentStatus,
  'duration' : IDL.Nat,
  'clientId' : IDL.Nat,
  'notes' : IDL.Text,
  'dateTime' : Time,
});
export const BusinessType = IDL.Variant({
  'clinic' : IDL.Null,
  'barber' : IDL.Null,
  'salon' : IDL.Null,
  'petshop' : IDL.Null,
});
export const Client = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'businessType' : BusinessType,
  'email' : IDL.Text,
  'lastVisit' : Time,
  'notes' : IDL.Text,
  'totalVisits' : IDL.Nat,
  'phone' : IDL.Text,
});
export const FinancialType = IDL.Variant({
  'expense' : IDL.Null,
  'income' : IDL.Null,
});
export const FinancialRecord = IDL.Record({
  'id' : IDL.Nat,
  'linkedAppointmentId' : IDL.Opt(IDL.Nat),
  'date' : Time,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
  'financialType' : FinancialType,
});
export const Reminder = IDL.Record({
  'clientName' : IDL.Text,
  'appointmentTime' : IDL.Int,
  'reminderType' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'createAppointment' : IDL.Func(
      [IDL.Nat, IDL.Text, Time, IDL.Nat, IDL.Text],
      [Appointment],
      [],
    ),
  'createClient' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, BusinessType],
      [Client],
      [],
    ),
  'createFinancialRecord' : IDL.Func(
      [FinancialType, IDL.Float64, IDL.Text, Time, IDL.Text, IDL.Opt(IDL.Nat)],
      [FinancialRecord],
      [],
    ),
  'deleteAppointment' : IDL.Func([IDL.Nat], [], []),
  'deleteClient' : IDL.Func([IDL.Nat], [], []),
  'deleteFinancialRecord' : IDL.Func([IDL.Nat], [], []),
  'generateMessageTemplates' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'generateReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
  'getAppointment' : IDL.Func([IDL.Nat], [Appointment], ['query']),
  'getClient' : IDL.Func([IDL.Nat], [Client], ['query']),
  'getClientsNotVisitedSince' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Client)],
      ['query'],
    ),
  'getFinancialRecord' : IDL.Func([IDL.Nat], [FinancialRecord], ['query']),
  'getTopClientsByVisits' : IDL.Func([IDL.Nat], [IDL.Vec(Client)], ['query']),
  'getTotalAppointments' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalClients' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalFinancialRecords' : IDL.Func([], [IDL.Nat], ['query']),
  'updateAppointmentStatus' : IDL.Func(
      [IDL.Nat, AppointmentStatus],
      [Appointment],
      [],
    ),
  'updateClient' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, BusinessType, IDL.Text],
      [Client],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const AppointmentStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'id' : IDL.Nat,
    'service' : IDL.Text,
    'status' : AppointmentStatus,
    'duration' : IDL.Nat,
    'clientId' : IDL.Nat,
    'notes' : IDL.Text,
    'dateTime' : Time,
  });
  const BusinessType = IDL.Variant({
    'clinic' : IDL.Null,
    'barber' : IDL.Null,
    'salon' : IDL.Null,
    'petshop' : IDL.Null,
  });
  const Client = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'businessType' : BusinessType,
    'email' : IDL.Text,
    'lastVisit' : Time,
    'notes' : IDL.Text,
    'totalVisits' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const FinancialType = IDL.Variant({
    'expense' : IDL.Null,
    'income' : IDL.Null,
  });
  const FinancialRecord = IDL.Record({
    'id' : IDL.Nat,
    'linkedAppointmentId' : IDL.Opt(IDL.Nat),
    'date' : Time,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
    'financialType' : FinancialType,
  });
  const Reminder = IDL.Record({
    'clientName' : IDL.Text,
    'appointmentTime' : IDL.Int,
    'reminderType' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    'createAppointment' : IDL.Func(
        [IDL.Nat, IDL.Text, Time, IDL.Nat, IDL.Text],
        [Appointment],
        [],
      ),
    'createClient' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, BusinessType],
        [Client],
        [],
      ),
    'createFinancialRecord' : IDL.Func(
        [
          FinancialType,
          IDL.Float64,
          IDL.Text,
          Time,
          IDL.Text,
          IDL.Opt(IDL.Nat),
        ],
        [FinancialRecord],
        [],
      ),
    'deleteAppointment' : IDL.Func([IDL.Nat], [], []),
    'deleteClient' : IDL.Func([IDL.Nat], [], []),
    'deleteFinancialRecord' : IDL.Func([IDL.Nat], [], []),
    'generateMessageTemplates' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'generateReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
    'getAppointment' : IDL.Func([IDL.Nat], [Appointment], ['query']),
    'getClient' : IDL.Func([IDL.Nat], [Client], ['query']),
    'getClientsNotVisitedSince' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Client)],
        ['query'],
      ),
    'getFinancialRecord' : IDL.Func([IDL.Nat], [FinancialRecord], ['query']),
    'getTopClientsByVisits' : IDL.Func([IDL.Nat], [IDL.Vec(Client)], ['query']),
    'getTotalAppointments' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalClients' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalFinancialRecords' : IDL.Func([], [IDL.Nat], ['query']),
    'updateAppointmentStatus' : IDL.Func(
        [IDL.Nat, AppointmentStatus],
        [Appointment],
        [],
      ),
    'updateClient' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, BusinessType, IDL.Text],
        [Client],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };