/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : bigint,
  'service' : string,
  'status' : AppointmentStatus,
  'duration' : bigint,
  'clientId' : bigint,
  'notes' : string,
  'dateTime' : Time,
}
export type AppointmentStatus = { 'scheduled' : null } |
  { 'cancelled' : null } |
  { 'completed' : null };
export type BusinessType = { 'clinic' : null } |
  { 'barber' : null } |
  { 'salon' : null } |
  { 'petshop' : null };
export interface Client {
  'id' : bigint,
  'name' : string,
  'businessType' : BusinessType,
  'email' : string,
  'lastVisit' : Time,
  'notes' : string,
  'totalVisits' : bigint,
  'phone' : string,
}
export interface FinancialRecord {
  'id' : bigint,
  'linkedAppointmentId' : [] | [bigint],
  'date' : Time,
  'description' : string,
  'category' : string,
  'amount' : number,
  'financialType' : FinancialType,
}
export type FinancialType = { 'expense' : null } |
  { 'income' : null };
export interface Reminder {
  'clientName' : string,
  'appointmentTime' : bigint,
  'reminderType' : string,
  'message' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'createAppointment' : ActorMethod<
    [bigint, string, Time, bigint, string],
    Appointment
  >,
  'createClient' : ActorMethod<[string, string, string, BusinessType], Client>,
  'createFinancialRecord' : ActorMethod<
    [FinancialType, number, string, Time, string, [] | [bigint]],
    FinancialRecord
  >,
  'deleteAppointment' : ActorMethod<[bigint], undefined>,
  'deleteClient' : ActorMethod<[bigint], undefined>,
  'deleteFinancialRecord' : ActorMethod<[bigint], undefined>,
  'generateMessageTemplates' : ActorMethod<[bigint, bigint], Array<string>>,
  'generateReminders' : ActorMethod<[], Array<Reminder>>,
  'getAppointment' : ActorMethod<[bigint], Appointment>,
  'getClient' : ActorMethod<[bigint], Client>,
  'getClientsNotVisitedSince' : ActorMethod<[bigint], Array<Client>>,
  'getFinancialRecord' : ActorMethod<[bigint], FinancialRecord>,
  'getTopClientsByVisits' : ActorMethod<[bigint], Array<Client>>,
  'getTotalAppointments' : ActorMethod<[], bigint>,
  'getTotalClients' : ActorMethod<[], bigint>,
  'getTotalFinancialRecords' : ActorMethod<[], bigint>,
  'updateAppointmentStatus' : ActorMethod<
    [bigint, AppointmentStatus],
    Appointment
  >,
  'updateClient' : ActorMethod<
    [bigint, string, string, string, BusinessType, string],
    Client
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];